service: headlines-aliyun
frameworkVersion: "2"
custom:
  webpack:
    webpackConfig: "./webpack.config.js"
    includeModules: true
  bucketName: my-unique-named-bucket
plugins:
  - serverless-webpack
  - serverless-aliyun-function-compute
package:
  artifact: ./serverless/headlines-aliyun.zip
provider:
  name: aliyun
  runtime: nodejs12
  region: ap-southeast-2
  credentials: ~/.aliyuncli/credentials
  ramRoleStatements:
    - Effect: Allow
      Action:
        - oss:PutObject
      Resource:
        - "acs:oss:*:*:${self:custom.bucketName}/*"
functions:
  parseFeed:
    handler: src/parseFeed.handle
    environmentVariables:
      BUCKET_NAME: "${self:custom.bucketName}"
    events:
      - timer:
          triggerConfig:
            cronExpression: "0 0 * * * *"
            enabled: true
