service: headlines-aliyun
frameworkVersion: "2"
custom:
  webpack:
    webpackConfig: "./webpack.config.js"
    includeModules: true
plugins:
  - serverless-webpack
  - serverless-aliyun-function-compute
package:
  artifact: ./serverless/headlines-aliyun.zip
provider:
  name: aliyun
  runtime: nodejs12
  region: ap-southeast-2
  credentials: ~/.aliyuncli/credentials
functions:
  parseFeed:
    handler: src/parseFeed.handle
    events:
      - timer:
          triggerConfig:
            cronExpression: "0 0 * * * *"
            enabled: true
